name: Release

on:
  - push

jobs:
  release-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git push origin :refs/tags/${{ github.ref_name }}-rc --force
      - uses: ncipollo/release-action@v1.12.0
        with:
          tag:  ${{ github.ref_name }}-rc
          commit: ${{ github.sha }}
          generateReleaseNotes: true
          makeLatest: false
          draft: false
          prerelease: true
          allowUpdates: true
          updateOnlyUnreleased: true
